# Generated by Django 4.2.7 on 2023-11-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SafetyIndicator",
            fields=[
                (
                    "si_id",
                    models.BigAutoField(
                        db_comment="安全指标ID", primary_key=True, serialize=False
                    ),
                ),
                ("si_category", models.CharField(db_comment="指标分类", max_length=30)),
                ("si_name", models.CharField(db_comment="安全指标名称", max_length=30)),
                ("si_state", models.IntegerField(db_comment="安全指标状态")),
                ("si_creator", models.CharField(db_comment="安全指标创建人", max_length=30)),
                ("si_create_time", models.DateTimeField(db_comment="安全指标创建时间")),
            ],
            options={
                "db_table": "safety_indicator",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "scene_id",
                    models.BigAutoField(
                        db_comment="场景ID", primary_key=True, serialize=False
                    ),
                ),
                ("scene_name", models.CharField(db_comment="场景名称", max_length=30)),
                ("scene_state", models.IntegerField(db_comment="场景状态")),
                (
                    "scene_description",
                    models.CharField(db_comment="场景描述", max_length=200),
                ),
                ("scene_creator", models.CharField(db_comment="场景创建人", max_length=30)),
                ("scene_create_time", models.DateTimeField(db_comment="场景创建时间")),
            ],
            options={
                "db_table": "scene",
                "managed": True,
            },
        ),
    ]
