# Generated by Django 4.2.7 on 2023-11-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetyindicator",
            name="si_id",
            field=models.IntegerField(
                db_comment="安全指标ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="scene_id",
            field=models.IntegerField(
                db_comment="场景ID", primary_key=True, serialize=False
            ),
        ),
    ]
