# Generated by Django 4.2.7 on 2023-11-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_taskstatetable_alter_task_task_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="product_ad",
            field=models.ImageField(
                blank=True,
                db_column="product_AD",
                db_comment="产品架构图",
                null=True,
                upload_to="images/",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="product_td",
            field=models.ImageField(
                blank=True,
                db_column="product_TD",
                db_comment="产品拓扑图",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
