# Generated by Django 4.2.4 on 2023-11-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_task_product_ad_alter_task_product_td"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksi",
            name="si",
            field=models.ForeignKey(
                db_comment="安全指标ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="news.safetyindicator",
            ),
        ),
        migrations.AlterField(
            model_name="tasksi",
            name="task",
            field=models.OneToOneField(
                db_comment="任务ID",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="news.task",
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user2",
        ),
    ]
