# Generated by Django 4.2.4 on 2023-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_user_id_alter_user_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(
                db_comment="用户ID", primary_key=True, serialize=False
            ),
        ),
    ]
