# Generated by Django 4.2.7 on 2023-11-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.IntegerField(
                        db_comment="用户ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_account",
                    models.CharField(db_comment="用户账号", max_length=30, unique=True),
                ),
                ("user_password", models.CharField(db_comment="用户密码", max_length=30)),
                (
                    "user_name",
                    models.CharField(db_comment="用户账号", max_length=20, unique=True),
                ),
                ("user_authority", models.IntegerField(db_comment="用户权限")),
                (
                    "user_email",
                    models.CharField(
                        blank=True, db_comment="用户邮箱", max_length=30, null=True
                    ),
                ),
                (
                    "user_phone",
                    models.IntegerField(blank=True, db_comment="用户电话号码", null=True),
                ),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
    ]
