# Generated by Django 4.2.7 on 2023-11-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_user_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStateTable",
            fields=[
                (
                    "task_state_id",
                    models.IntegerField(
                        db_comment="任务状态", primary_key=True, serialize=False
                    ),
                ),
                (
                    "task_state_name",
                    models.CharField(db_comment="任务状态名称", max_length=30),
                ),
            ],
            options={"db_table": "task_state_table", "managed": True,},
        ),
        migrations.AlterField(
            model_name="task",
            name="task_state",
            field=models.ForeignKey(
                db_column="task_state",
                db_comment="任务状态",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="news.taskstatetable",
            ),
        ),
    ]
